In [ ]:
!pip uninstall scikit-learn
!pip install scikit-learn==0.24.2

Found existing installation: scikit-learn 1.0.2
Uninstalling scikit-learn-1.0.2:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/scikit_learn-1.0.2.dist-info/*
    /usr/local/lib/python3.7/dist-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
    /usr/local/lib/python3.7/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-1.0.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 22.3 MB 4.0 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.


##Preprocesamiento - Data

##Data

In [ ]:
#Descargar excel desde link de Drive
!gdown --id text

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("Data-Osiptel.xlsx", sheet_name="Entel")
data.head(5)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                      6.433333   
1    1   10                                      2.166667   
2    1   11                                      3.566667   
3    1   12                                      3.500000   
4    1    1                                     16.183333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   
1                                9807.0  0.000221   
2                                9292.5  0.000384   
3                                9526.5  0.000367   
4                                9680.5  0.001672   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      
1                                            16910.0      
2                                            16863.0      
3                                            11868.0      
4                                            10389.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   
1                                84763.0  0.199497   
2                                86335.0  0.195321   
3                                74383.0  0.159553   
4                                72254.0  0.143784   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   
1                                       21615.0   
2                                       30124.0   
3                                       21069.0   
4                                       19867.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)  Reclamos     Bajas  Consultas  \
0                        338717.0  0.148153  0.631699  0.715072   0.656096   
1                        644556.0  0.033535  0.410101  0.468876   0.448331   
2                        539400.0  0.055847  0.377196  0.437500   0.438256   
3                        582133.0  0.036193  0.448555  0.541643   0.548162   
4                        492719.0  0.040321  0.468233  0.515502   0.563666   

      Altas  
0  0.808229  
1  0.527333  
2  0.623783  
3  0.750687  
4  0.762664

In [ ]:
#IMPUTACION
from sklearn.impute import SimpleImputer
simple = SimpleImputer().fit(data)
df_imputed = simple.transform(data)
df_imputed = pd.DataFrame(df_imputed, columns=data.columns)
data = df_imputed
data

AÑO   Mes  N° de horas sin sistema de atención al mes    \
0   1.0   9.0                                      6.433333   
1   1.0  10.0                                      2.166667   
2   1.0  11.0                                      3.566667   
3   1.0  12.0                                      3.500000   
4   1.0   1.0                                     16.183333   
5   1.0   2.0                                     29.716667   
6   1.0   3.0                                      1.233333   
7   1.0   4.0                                      0.000000   
8   1.0   5.0                                      0.000000   
9   1.0   6.0                                      5.650000   
10  1.0   7.0                                     13.550000   
11  1.0   8.0                                     13.200000   
12  2.0   9.0                                      3.650000   
13  2.0  10.0                                     25.566667   
14  2.0  11.0                                     26.200000   
15  2.0  12.0                                      3.650000   
16  2.0   1.0                                      8.550000   
17  2.0   2.0                                      2.450000   
18  2.0   3.0                                      2.916667   
19  2.0   4.0                                      7.200000   
20  2.0   5.0                                      8.450000   
21  2.0   6.0                                     18.650000   
22  2.0   7.0                                      0.283333   
23  2.0   8.0                                      7.766667   
24  3.0   9.0                                      6.316667   
25  3.0  10.0                                      1.740000   
26  3.0  11.0                                      8.316667   
27  3.0  12.0                                      0.000000   
28  3.0   1.0                                      3.030000   
29  3.0   2.0                                      2.866667   
30  3.0   3.0                                     33.700000   
31  3.0   4.0                                      2.666667   
32  3.0   5.0                                      3.683333   
33  3.0   6.0                                      1.580000   
34  3.0   7.0                                      0.000000   
35  3.0   8.0                                      3.016667   
36  4.0   9.0                                      2.933333   
37  4.0  10.0                                      6.722619   
38  4.0  11.0                                      6.722619   
39  4.0  12.0                                      0.000000   
40  4.0   1.0                                      0.000000   
41  4.0   2.0                                      1.183333   
42  4.0   3.0                                      0.000000   
43  4.0   4.0                                      0.783333   

    N° total de horas de atención al mes      CSA%  \
0                            9429.000000  0.000682   
1                            9807.000000  0.000221   
2                            9292.500000  0.000384   
3                            9526.500000  0.000367   
4                            9680.500000  0.001672   
5                            8998.000000  0.003303   
6                            9868.000000  0.000125   
7                            9767.000000  0.000000   
8                            9485.000000  0.000000   
9                            9473.500000  0.000596   
10                           9473.500000  0.001430   
11                          11079.500000  0.001191   
12                          11195.000000  0.000398   
13                          11151.500000  0.002412   
14                          10883.500000  0.003162   
15                          11195.000000  0.000398   
16                          10926.000000  0.000982   
17                          11048.500000  0.000274   
18                          11933.500000  0.000309   
19                          11327.500000  0.000803   
20                          11651.

In [ ]:
data["Reclamos"]

0     0.631699
1     0.410101
2     0.377196
3     0.448555
4     0.468233
5     0.459780
6     0.479005
7     0.465691
8     0.502797
9     0.534981
10    0.615804
11    0.563170
12    0.495330
13    0.543193
14    0.529268
15    0.495330
16    0.555169
17    0.554207
18    0.627927
19    0.589407
20    0.601727
21    0.582836
22    0.568421
23    0.547166
24    0.634547
25    0.716680
26    0.787015
27    0.720719
28    0.733620
29    0.832352
30    0.758600
31    0.773094
32    0.761682
33    0.752563
34    0.693252
35    0.767544
36    0.820102
37    0.625928
38    0.625928
39    0.749471
40    0.794816
41    0.775907
42    0.811104
43    0.758904
Name: Reclamos, dtype: float64

In [ ]:
bins = [0.00, 0.20, 0.40, 0.60, 0.80, 1.0]
names = ["1", "2", "3", "4", "5"]

In [ ]:
data["Reclamos-Cat"] = pd.cut(data["Reclamos"], bins, labels = names)
data[["Reclamos", "Reclamos-Cat"]].head(5)

Reclamos Reclamos-Cat
0  0.631699            4
1  0.410101            3
2  0.377196            2
3  0.448555            3
4  0.468233            3

In [ ]:
data = data.drop(['Reclamos'], axis=1)
data.head(5)

AÑO   Mes  N° de horas sin sistema de atención al mes    \
0  1.0   9.0                                      6.433333   
1  1.0  10.0                                      2.166667   
2  1.0  11.0                                      3.566667   
3  1.0  12.0                                      3.500000   
4  1.0   1.0                                     16.183333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   
1                                9807.0  0.000221   
2                                9292.5  0.000384   
3                                9526.5  0.000367   
4                                9680.5  0.001672   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      
1                                            16910.0      
2                                            16863.0      
3                                            11868.0      
4                                            10389.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   
1                                84763.0  0.199497   
2                                86335.0  0.195321   
3                                74383.0  0.159553   
4                                72254.0  0.143784   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   
1                                       21615.0   
2                                       30124.0   
3                                       21069.0   
4                                       19867.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  \
0                        338717.0  0.148153  0.715072   0.656096  0.808229   
1                        644556.0  0.033535  0.468876   0.448331  0.527333   
2                        539400.0  0.055847  0.437500   0.438256  0.623783   
3                        582133.0  0.036193  0.541643   0.548162  0.750687   
4                        492719.0  0.040321  0.515502   0.563666  0.762664   

  Reclamos-Cat  
0            4  
1            3  
2            2  
3            3  
4            3

In [ ]:
data["Reclamos-Cat"].value_counts().sort_index()

1     0
2     1
3    19
4    21
5     3
Name: Reclamos-Cat, dtype: int64

#XGboost - Shrinkage (alpha - lambda)

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  
0                        338717.0  0.148153  0.715072   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [2 2]]
Precisión del modelo: 0.8571428571428572
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.75
Curva ROC - AUC del modelo: 0.75


##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  
0                        338717.0  0.148153  0.715072   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [2 2]]
Precisión del modelo: 0.8571428571428572
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.75
Curva ROC - AUC del modelo: 0.75


##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  
0                        338717.0  0.148153  0.715072   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [2 2]]
Precisión del modelo: 0.8571428571428572
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.75
Curva ROC - AUC del modelo: 0.75


##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  
0                        338717.0  0.148153  0.715072   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [2 2]]
Precisión del modelo: 0.8571428571428572
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.75
Curva ROC - AUC del modelo: 0.75


#XGboost - Con RFE

##RFE

In [ ]:
from sklearn import linear_model
from time import time
import numpy as np
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

df = data.dropna()
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

#######################################
#no of features
nof_list=np.arange(1,14)            
high_score=0
#Variable to store the optimum features
nof=0           
score_list =[]
for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)
    model = LinearRegression()
    rfe = RFE(model,nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)
    score = model.score(X_test_rfe,y_test)
    score_list.append(score)
    if(score>high_score):
        high_score = score
        nof = nof_list[n]
print("Optimum number of features: %d" %nof)
print("Score with %d features: %f" % (nof, high_score))
#########################################
cols = list(X.columns)
model = LinearRegression()
#Initializing RFE model
rfe = RFE(model, 13)             
#Transforming data using RFE
X_rfe = rfe.fit_transform(X,Y)  
#Fitting the data to model
model.fit(X_rfe,Y)              
temp = pd.Series(rfe.support_,index = cols)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Optimum number of features: 13
Score with 13 features: 0.544633
Index(['AÑO', 'Mes', 'N° de horas sin sistema de atención al mes  ',
       'N° total de horas de atención al mes', 'CSA%',
       'Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES',
       'Nº TOTAL DE USUARIOS ATENDIDOS AL MES', 'DAP (%)',
       'Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO', 'CAT (%)', 'Bajas',
       'Consultas', 'Altas'],
      dtype='object')


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=4 as keyword args. From version 1.0 (renaming of 0.25) passing these 

In [ ]:
"""
Variable Eliminada:

Nº TOTAL DE LLAMADAS ATENDIDAS
"""

'\nVariable Eliminada:\n\nNº TOTAL DE LLAMADAS ATENDIDAS\n'

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat', 'Nº TOTAL DE LLAMADAS ATENDIDAS'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO   CAT (%)     Bajas  \
0                                       50182.0  0.148153  0.715072   

   Consultas     Altas  
0   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [2 2]]
Precisión del modelo: 0.8571428571428572
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.75
Curva ROC - AUC del modelo: 0.75


##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat', 'Nº TOTAL DE LLAMADAS ATENDIDAS'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO   CAT (%)     Bajas  \
0                                       50182.0  0.148153  0.715072   

   Consultas     Altas  
0   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [2 2]]
Precisión del modelo: 0.8571428571428572
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.75
Curva ROC - AUC del modelo: 0.75


##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat', 'Nº TOTAL DE LLAMADAS ATENDIDAS'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO   CAT (%)     Bajas  \
0                                       50182.0  0.148153  0.715072   

   Consultas     Altas  
0   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [2 2]]
Precisión del modelo: 0.8571428571428572
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.75
Curva ROC - AUC del modelo: 0.75


##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat', 'Nº TOTAL DE LLAMADAS ATENDIDAS'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO   CAT (%)     Bajas  \
0                                       50182.0  0.148153  0.715072   

   Consultas     Altas  
0   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [2 2]]
Precisión del modelo: 0.8571428571428572
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.75
Curva ROC - AUC del modelo: 0.75
