In [ ]:
!pip uninstall scikit-learn
!pip install scikit-learn==0.24.2

Found existing installation: scikit-learn 1.0.2
Uninstalling scikit-learn-1.0.2:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/scikit_learn-1.0.2.dist-info/*
    /usr/local/lib/python3.7/dist-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
    /usr/local/lib/python3.7/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-1.0.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 22.3 MB 1.3 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.


##Preprocesamiento - Data

In [ ]:
#Descargar excel desde link de Drive
!gdown --id 1s9jAV8BDz3eUo8sV9R0pmXEQbTurf-gd

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("Data-Osiptel.xlsx", sheet_name="Entel")
data.head(5)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                      6.433333   
1    1   10                                      2.166667   
2    1   11                                      3.566667   
3    1   12                                      3.500000   
4    1    1                                     16.183333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   
1                                9807.0  0.000221   
2                                9292.5  0.000384   
3                                9526.5  0.000367   
4                                9680.5  0.001672   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      
1                                            16910.0      
2                                            16863.0      
3                                            11868.0      
4                                            10389.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   
1                                84763.0  0.199497   
2                                86335.0  0.195321   
3                                74383.0  0.159553   
4                                72254.0  0.143784   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   
1                                       21615.0   
2                                       30124.0   
3                                       21069.0   
4                                       19867.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)  Reclamos     Bajas  Consultas  \
0                        338717.0  0.148153  0.631699  0.715072   0.656096   
1                        644556.0  0.033535  0.410101  0.468876   0.448331   
2                        539400.0  0.055847  0.377196  0.437500   0.438256   
3                        582133.0  0.036193  0.448555  0.541643   0.548162   
4                        492719.0  0.040321  0.468233  0.515502   0.563666   

      Altas  
0  0.808229  
1  0.527333  
2  0.623783  
3  0.750687  
4  0.762664

In [ ]:
data["Reclamos"]

0     0.631699
1     0.410101
2     0.377196
3     0.448555
4     0.468233
5     0.459780
6     0.479005
7     0.465691
8     0.502797
9     0.534981
10    0.615804
11    0.563170
12    0.495330
13    0.543193
14    0.529268
15    0.495330
16    0.555169
17    0.554207
18    0.627927
19    0.589407
20    0.601727
21    0.582836
22    0.568421
23    0.547166
24    0.634547
25    0.716680
26    0.787015
27    0.720719
28    0.733620
29    0.832352
30    0.758600
31    0.773094
32    0.761682
33    0.752563
34    0.693252
35    0.767544
36    0.820102
37         NaN
38         NaN
39    0.749471
40    0.794816
41    0.775907
42    0.811104
43    0.758904
Name: Reclamos, dtype: float64

In [ ]:
bins = [0.00, 0.20, 0.40, 0.60, 0.80, 1.0]
names = ["1", "2", "3", "4", "5"]

In [ ]:
data["Reclamos-Cat"] = pd.cut(data["Reclamos"], bins, labels = names)
data[["Reclamos", "Reclamos-Cat"]].head(5)

Reclamos Reclamos-Cat
0  0.631699            4
1  0.410101            3
2  0.377196            2
3  0.448555            3
4  0.468233            3

In [ ]:
data = data.drop(['Reclamos'], axis=1)
data.head(5)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                      6.433333   
1    1   10                                      2.166667   
2    1   11                                      3.566667   
3    1   12                                      3.500000   
4    1    1                                     16.183333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   
1                                9807.0  0.000221   
2                                9292.5  0.000384   
3                                9526.5  0.000367   
4                                9680.5  0.001672   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      
1                                            16910.0      
2                                            16863.0      
3                                            11868.0      
4                                            10389.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   
1                                84763.0  0.199497   
2                                86335.0  0.195321   
3                                74383.0  0.159553   
4                                72254.0  0.143784   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   
1                                       21615.0   
2                                       30124.0   
3                                       21069.0   
4                                       19867.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  \
0                        338717.0  0.148153  0.715072   0.656096  0.808229   
1                        644556.0  0.033535  0.468876   0.448331  0.527333   
2                        539400.0  0.055847  0.437500   0.438256  0.623783   
3                        582133.0  0.036193  0.541643   0.548162  0.750687   
4                        492719.0  0.040321  0.515502   0.563666  0.762664   

  Reclamos-Cat  
0            4  
1            3  
2            2  
3            3  
4            3

In [ ]:
data["Reclamos-Cat"].value_counts().sort_index()

1     0
2     1
3    19
4    19
5     3
Name: Reclamos-Cat, dtype: int64

#XGboost - Shrinkage (alpha - lambda)

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  
0                        338717.0  0.148153  0.715072   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[3 0]
 [1 5]]
Precisión del modelo: 0.875
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.9166666666666667
Puntaje F1 del modelo: 0.8831168831168831
Curva ROC - AUC del modelo: 0.9166666666666667


##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  
0                        338717.0  0.148153  0.715072   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[3 0]
 [1 5]]
Precisión del modelo: 0.875
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.9166666666666667
Puntaje F1 del modelo: 0.8831168831168831
Curva ROC - AUC del modelo: 0.9166666666666667


##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  
0                        338717.0  0.148153  0.715072   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[3 0]
 [1 5]]
Precisión del modelo: 0.875
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.9166666666666667
Puntaje F1 del modelo: 0.8831168831168831
Curva ROC - AUC del modelo: 0.9166666666666667


##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                      6.433333   

   N° total de horas de atención al mes      CSA%  \
0                                9429.0  0.000682   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                             4989.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                51894.0  0.096138   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                       50182.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS   CAT (%)     Bajas  Consultas     Altas  
0                        338717.0  0.148153  0.715072   0.656096  0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[3 0]
 [1 5]]
Precisión del modelo: 0.875
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.9166666666666667
Puntaje F1 del modelo: 0.8831168831168831
Curva ROC - AUC del modelo: 0.9166666666666667


#XGboost - Con RFE

##RFE

In [ ]:
from sklearn import linear_model
from time import time
import numpy as np
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

df = data.dropna()
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

#######################################
#no of features
nof_list=np.arange(1,14)            
high_score=0
#Variable to store the optimum features
nof=0           
score_list =[]
for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)
    model = LinearRegression()
    rfe = RFE(model,nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)
    score = model.score(X_test_rfe,y_test)
    score_list.append(score)
    if(score>high_score):
        high_score = score
        nof = nof_list[n]
print("Optimum number of features: %d" %nof)
print("Score with %d features: %f" % (nof, high_score))
#########################################
cols = list(X.columns)
model = LinearRegression()
#Initializing RFE model
rfe = RFE(model, 2)             
#Transforming data using RFE
X_rfe = rfe.fit_transform(X,Y)  
#Fitting the data to model
model.fit(X_rfe,Y)              
temp = pd.Series(rfe.support_,index = cols)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "w

Optimum number of features: 2
Score with 2 features: 0.726037
Index(['CSA%', 'Consultas'], dtype='object')


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=13 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['CSA%', 'Consultas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

CSA%  Consultas
0  0.000682   0.656096

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[3 0]
 [0 6]]
Precisión del modelo: 1.0
Exactitud del modelo: 1.0
Sensibilidad del modelo: 1.0
Puntaje F1 del modelo: 1.0
Curva ROC - AUC del modelo: 1.0


##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['CSA%', 'Consultas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

CSA%  Consultas
0  0.000682   0.656096

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[3 0]
 [0 6]]
Precisión del modelo: 1.0
Exactitud del modelo: 1.0
Sensibilidad del modelo: 1.0
Puntaje F1 del modelo: 1.0
Curva ROC - AUC del modelo: 1.0


##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['CSA%', 'Consultas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

CSA%  Consultas
0  0.000682   0.656096

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[3 0]
 [0 6]]
Precisión del modelo: 1.0
Exactitud del modelo: 1.0
Sensibilidad del modelo: 1.0
Puntaje F1 del modelo: 1.0
Curva ROC - AUC del modelo: 1.0


##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['CSA%', 'Consultas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

CSA%  Consultas
0  0.000682   0.656096

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[3 0]
 [0 6]]
Precisión del modelo: 1.0
Exactitud del modelo: 1.0
Sensibilidad del modelo: 1.0
Puntaje F1 del modelo: 1.0
Curva ROC - AUC del modelo: 1.0
