In [ ]:
!pip uninstall scikit-learn
!pip install scikit-learn==0.24.2

Found existing installation: scikit-learn 1.0.2
Uninstalling scikit-learn-1.0.2:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/scikit_learn-1.0.2.dist-info/*
    /usr/local/lib/python3.7/dist-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
    /usr/local/lib/python3.7/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-1.0.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 22.3 MB 1.9 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.


##Preprocesamiento - Data

In [ ]:
#Descargar excel desde link de Drive
!gdown --id 1s9jAV8BDz3eUo8sV9R0pmXEQbTurf-gd

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("Data-Osiptel.xlsx", sheet_name="Telefonica")
data.head(5)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                          0.00   
1    1   10                                          0.00   
2    1   11                                          0.00   
3    1   12                                         10.56   
4    1    1                                          0.00   

   N° total de horas de atención al mes    CSA%  \
0                                8529.0  0.0000   
1                               26209.5  0.0000   
2                               25691.0  0.0000   
3                               26503.0  0.0004   
4                               26881.0  0.0000   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                               4370      
1                                              26101      
2                                              29482      
3                                              32598      
4                                              29384      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                  99252  0.044029   
1                                 596323  0.043770   
2                                 585633  0.050342   
3                                 607136  0.053691   
4                                 613609  0.047887   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                         88128   
1                                        326554   
2                                        249708   
3                                        308521   
4                                        347867   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)  Reclamos  Bajas  Consultas  Altas  
0                         1677328   0.0525      0.76   0.79       0.78   0.95  
1                         5340026   0.0612      0.74   0.76       0.78   0.94  
2                         4016975   0.0622      0.72   0.70       0.74   0.92  
3                         4263226   0.0724      0.69   0.67       0.71   0.93  
4                         4100981   0.0848      0.67   0.69       0.74   0.91

In [ ]:
data["Reclamos"]

0     0.76
1     0.74
2     0.72
3     0.69
4     0.67
5     0.72
6     0.72
7     0.67
8     0.77
9     0.78
10    0.77
11    0.76
12    0.81
13    0.83
14    0.82
15    0.74
16    0.79
17    0.77
18    0.80
19    0.81
20    0.84
21    0.78
22    0.75
23    0.56
24    0.65
25    0.82
26    0.83
27    0.84
28    0.69
29    0.73
30    0.81
31    0.70
32    0.81
33    0.87
34    0.86
35    0.80
36    0.86
37    0.88
38    0.79
39    0.80
40    0.80
41    0.80
42    0.71
43    0.70
Name: Reclamos, dtype: float64

In [ ]:
bins = [0.00, 0.20, 0.40, 0.60, 0.80, 1.0]
names = ["1", "2", "3", "4", "5"]

In [ ]:
data["Reclamos-Cat"] = pd.cut(data["Reclamos"], bins, labels = names)
data[["Reclamos", "Reclamos-Cat"]].head(5)

Reclamos Reclamos-Cat
0      0.76            4
1      0.74            4
2      0.72            4
3      0.69            4
4      0.67            4

In [ ]:
data = data.drop(['Reclamos'], axis=1)
data.head(5)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                          0.00   
1    1   10                                          0.00   
2    1   11                                          0.00   
3    1   12                                         10.56   
4    1    1                                          0.00   

   N° total de horas de atención al mes    CSA%  \
0                                8529.0  0.0000   
1                               26209.5  0.0000   
2                               25691.0  0.0000   
3                               26503.0  0.0004   
4                               26881.0  0.0000   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                               4370      
1                                              26101      
2                                              29482      
3                                              32598      
4                                              29384      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                  99252  0.044029   
1                                 596323  0.043770   
2                                 585633  0.050342   
3                                 607136  0.053691   
4                                 613609  0.047887   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                         88128   
1                                        326554   
2                                        249708   
3                                        308521   
4                                        347867   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)  Bajas  Consultas  Altas  \
0                         1677328   0.0525   0.79       0.78   0.95   
1                         5340026   0.0612   0.76       0.78   0.94   
2                         4016975   0.0622   0.70       0.74   0.92   
3                         4263226   0.0724   0.67       0.71   0.93   
4                         4100981   0.0848   0.69       0.74   0.91   

  Reclamos-Cat  
0            4  
1            4  
2            4  
3            4  
4            4

In [ ]:
data["Reclamos-Cat"].value_counts().sort_index()

1     0
2     0
3     1
4    29
5    14
Name: Reclamos-Cat, dtype: int64

#XGboost - Shrinkage (alpha - lambda)

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                           0.0   

   N° total de horas de atención al mes  CSA%  \
0                                8529.0   0.0   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                               4370      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                  99252  0.044029   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                         88128   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)  Bajas  Consultas  Altas  
0                         1677328   0.0525   0.79       0.78   0.95

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 1]
 [0 2]]
Precisión del modelo: 0.8333333333333333
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.9285714285714286
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.9285714285714286


##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                           0.0   

   N° total de horas de atención al mes  CSA%  \
0                                8529.0   0.0   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                               4370      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                  99252  0.044029   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                         88128   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)  Bajas  Consultas  Altas  
0                         1677328   0.0525   0.79       0.78   0.95

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 1]
 [1 1]]
Precisión del modelo: 0.6785714285714286
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.6785714285714286
Puntaje F1 del modelo: 0.6785714285714286
Curva ROC - AUC del modelo: 0.6785714285714286


##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                           0.0   

   N° total de horas de atención al mes  CSA%  \
0                                8529.0   0.0   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                               4370      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                  99252  0.044029   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                         88128   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)  Bajas  Consultas  Altas  
0                         1677328   0.0525   0.79       0.78   0.95

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 1]
 [1 1]]
Precisión del modelo: 0.6785714285714286
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.6785714285714286
Puntaje F1 del modelo: 0.6785714285714286
Curva ROC - AUC del modelo: 0.6785714285714286


##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                           0.0   

   N° total de horas de atención al mes  CSA%  \
0                                8529.0   0.0   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                               4370      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES   DAP (%)  \
0                                  99252  0.044029   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                         88128   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)  Bajas  Consultas  Altas  
0                         1677328   0.0525   0.79       0.78   0.95

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 1]
 [1 1]]
Precisión del modelo: 0.6785714285714286
Exactitud del modelo: 0.7777777777777778
Sensibilidad del modelo: 0.6785714285714286
Puntaje F1 del modelo: 0.6785714285714286
Curva ROC - AUC del modelo: 0.6785714285714286


#XGboost - Con RFE

##RFE

In [ ]:
from sklearn import linear_model
from time import time
import numpy as np
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

df = data.dropna()
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

#######################################
#no of features
nof_list=np.arange(1,14)            
high_score=0
#Variable to store the optimum features
nof=0           
score_list =[]
for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)
    model = LinearRegression()
    rfe = RFE(model,nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)
    score = model.score(X_test_rfe,y_test)
    score_list.append(score)
    if(score>high_score):
        high_score = score
        nof = nof_list[n]
print("Optimum number of features: %d" %nof)
print("Score with %d features: %f" % (nof, high_score))
#########################################
cols = list(X.columns)
model = LinearRegression()
#Initializing RFE model
rfe = RFE(model, 7)             
#Transforming data using RFE
X_rfe = rfe.fit_transform(X,Y)  
#Fitting the data to model
model.fit(X_rfe,Y)              
temp = pd.Series(rfe.support_,index = cols)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "w

Optimum number of features: 7
Score with 7 features: 0.551912
Index(['AÑO', 'CSA%', 'DAP (%)', 'CAT (%)', 'Bajas', 'Consultas', 'Altas'], dtype='object')


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=13 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=7 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['AÑO', 'CSA%', 'DAP (%)', 'CAT (%)', 'Bajas', 'Consultas', 'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  CSA%   DAP (%)  CAT (%)  Bajas  Consultas  Altas
0    1   0.0  0.044029   0.0525   0.79       0.78   0.95

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 1]
 [0 2]]
Precisión del modelo: 0.8333333333333333
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.9285714285714286
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.9285714285714286


##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['AÑO', 'CSA%', 'DAP (%)', 'CAT (%)', 'Bajas', 'Consultas', 'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  CSA%   DAP (%)  CAT (%)  Bajas  Consultas  Altas
0    1   0.0  0.044029   0.0525   0.79       0.78   0.95

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[7 0]
 [1 1]]
Precisión del modelo: 0.9375
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.75
Puntaje F1 del modelo: 0.8
Curva ROC - AUC del modelo: 0.75


##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['AÑO', 'CSA%', 'DAP (%)', 'CAT (%)', 'Bajas', 'Consultas', 'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  CSA%   DAP (%)  CAT (%)  Bajas  Consultas  Altas
0    1   0.0  0.044029   0.0525   0.79       0.78   0.95

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 1]
 [0 2]]
Precisión del modelo: 0.8333333333333333
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.9285714285714286
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.9285714285714286


##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['AÑO', 'CSA%', 'DAP (%)', 'CAT (%)', 'Bajas', 'Consultas', 'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  CSA%   DAP (%)  CAT (%)  Bajas  Consultas  Altas
0    1   0.0  0.044029   0.0525   0.79       0.78   0.95

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[7 0]
 [0 2]]
Precisión del modelo: 1.0
Exactitud del modelo: 1.0
Sensibilidad del modelo: 1.0
Puntaje F1 del modelo: 1.0
Curva ROC - AUC del modelo: 1.0
