In [ ]:
!pip uninstall scikit-learn
!pip install scikit-learn==0.24.2

Found existing installation: scikit-learn 1.0.2
Uninstalling scikit-learn-1.0.2:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/scikit_learn-1.0.2.dist-info/*
    /usr/local/lib/python3.7/dist-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
    /usr/local/lib/python3.7/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-1.0.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 22.3 MB 1.4 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.


##Preprocesamiento - Data

##Data

In [ ]:
#Descargar excel desde link de Drive
!gdown --id text

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("Data-Osiptel.xlsx", sheet_name="Claro")
data.head(5)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0    1    9                                         15.12   
1    1   10                                         26.37   
2    1   11                                          3.58   
3    1   12                                          0.62   
4    1    1                                          0.83   

   N° total de horas de atención al mes      CSA%  \
0                              18518.00  0.000817   
1                              18591.50  0.001418   
2                              18637.25  0.000192   
3                              21049.75  0.000029   
4                              19743.50  0.000042   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                            41584.0      
1                                            37908.0      
2                                            37922.0      
3                                            39301.0      
4                                            35969.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES  DAP (%)  \
0                               493360.0   0.0843   
1                               506790.0   0.0748   
2                               508222.0   0.0746   
3                               518982.0   0.0757   
4                               506900.0   0.0710   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                      118385.0   
1                                      123382.0   
2                                      117383.0   
3                                       11756.0   
4                                      100277.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)  Reclamos   Bajas  Consultas  \
0                       3124089.0   0.0379    0.6390  0.6217     0.6588   
1                       3391270.0   0.0364    0.7334  0.6642     0.6597   
2                       3246056.0   0.0362    0.7112  0.6466     0.6270   
3                       3382625.0   0.0348    0.7378  0.6847     0.6490   
4                       3505628.0   0.0286    0.7641  0.7229     0.7189   

    Altas  
0  0.7507  
1  0.6445  
2  0.6292  
3  0.6697  
4  0.7044

In [ ]:
#IMPUTACION
from sklearn.impute import SimpleImputer
simple = SimpleImputer().fit(data)
df_imputed = simple.transform(data)
df_imputed = pd.DataFrame(df_imputed, columns=data.columns)
data = df_imputed
data

AÑO   Mes  N° de horas sin sistema de atención al mes    \
0   1.0   9.0                                     15.120000   
1   1.0  10.0                                     26.370000   
2   1.0  11.0                                      3.580000   
3   1.0  12.0                                      0.620000   
4   1.0   1.0                                      0.830000   
5   1.0   2.0                                      8.250000   
6   1.0   3.0                                      1.520000   
7   1.0   4.0                                      3.700000   
8   1.0   5.0                                      0.000000   
9   1.0   6.0                                      8.693953   
10  1.0   7.0                                      7.180000   
11  1.0   8.0                                      0.680000   
12  2.0   9.0                                     13.070000   
13  2.0  10.0                                      2.650000   
14  2.0  11.0                                      1.840000   
15  2.0  12.0                                     11.570000   
16  2.0   1.0                                      0.170000   
17  2.0   2.0                                      0.000000   
18  2.0   3.0                                      4.800000   
19  2.0   4.0                                      1.100000   
20  2.0   5.0                                     13.370000   
21  2.0   6.0                                      1.460000   
22  2.0   7.0                                      3.420000   
23  2.0   8.0                                     82.260000   
24  3.0   9.0                                     16.140000   
25  3.0  10.0                                      7.900000   
26  3.0  11.0                                     13.250000   
27  3.0  12.0                                     29.320000   
28  3.0   1.0                                     13.540000   
29  3.0   2.0                                     13.580000   
30  3.0   3.0                                     15.680000   
31  3.0   4.0                                     11.170000   
32  3.0   5.0                                     12.280000   
33  3.0   6.0                                      2.970000   
34  3.0   7.0                                      3.600000   
35  3.0   8.0                                      3.150000   
36  4.0   9.0                                      1.000000   
37  4.0  10.0                                      9.530000   
38  4.0  11.0                                      5.670000   
39  4.0  12.0                                      5.280000   
40  4.0   1.0                                      1.200000   
41  4.0   2.0                                      1.380000   
42  4.0   3.0                                      2.070000   
43  4.0   4.0                                      1.570000   

    N° total de horas de atención al mes      CSA%  \
0                           18518.000000  0.000817   
1                           18591.500000  0.001418   
2                           18637.250000  0.000192   
3                           21049.750000  0.000029   
4                           19743.500000  0.000042   
5                           18530.500000  0.000445   
6                           20930.750000  0.000073   
7                           19992.250000  0.000185   
8                           20780.250000  0.000000   
9                           21205.813953  0.000407   
10                          20583.750000  0.000349   
11                          20698.500000  0.000033   
12                          20791.000000  0.000629   
13                          20590.250000  0.000129   
14                          20453.750000  0.000090   
15                          21970.500000  0.000527   
16                          20970.500000  0.000008   
17                          20395.250000  0.000000   
18                          21421.500000  0.000224   
19                          21398.500000  0.000051   
20                          22022.

In [ ]:
data["Reclamos"]

0     0.639000
1     0.733400
2     0.711200
3     0.737800
4     0.764100
5     0.797000
6     0.787200
7     0.808400
8     0.789900
9     0.793083
10    0.813900
11    0.792700
12    0.836672
13    0.804647
14    0.787831
15    0.762627
16    0.793281
17    0.710258
18    0.731498
19    0.762041
20    0.790722
21    0.834782
22    0.796516
23    0.773877
24    0.763500
25    0.816100
26    0.857000
27    0.798800
28    0.830000
29    0.836900
30    0.873200
31    0.883900
32    0.827600
33    0.806100
34    0.790200
35    0.792100
36    0.827000
37    0.836100
38    0.850600
39    0.775200
40    0.788100
41    0.796500
42    0.785100
43    0.809200
Name: Reclamos, dtype: float64

In [ ]:
bins = [0.00, 0.20, 0.40, 0.60, 0.80, 1.0]
names = ["1", "2", "3", "4", "5"]

In [ ]:
data["Reclamos-Cat"] = pd.cut(data["Reclamos"], bins, labels = names)
data[["Reclamos", "Reclamos-Cat"]].head(5)

Reclamos Reclamos-Cat
0    0.6390            4
1    0.7334            4
2    0.7112            4
3    0.7378            4
4    0.7641            4

In [ ]:
data = data.drop(['Reclamos'], axis=1)
data.head(5)

AÑO   Mes  N° de horas sin sistema de atención al mes    \
0  1.0   9.0                                         15.12   
1  1.0  10.0                                         26.37   
2  1.0  11.0                                          3.58   
3  1.0  12.0                                          0.62   
4  1.0   1.0                                          0.83   

   N° total de horas de atención al mes      CSA%  \
0                              18518.00  0.000817   
1                              18591.50  0.001418   
2                              18637.25  0.000192   
3                              21049.75  0.000029   
4                              19743.50  0.000042   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                            41584.0      
1                                            37908.0      
2                                            37922.0      
3                                            39301.0      
4                                            35969.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES  DAP (%)  \
0                               493360.0   0.0843   
1                               506790.0   0.0748   
2                               508222.0   0.0746   
3                               518982.0   0.0757   
4                               506900.0   0.0710   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                      118385.0   
1                                      123382.0   
2                                      117383.0   
3                                       11756.0   
4                                      100277.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)   Bajas  Consultas   Altas  \
0                       3124089.0   0.0379  0.6217     0.6588  0.7507   
1                       3391270.0   0.0364  0.6642     0.6597  0.6445   
2                       3246056.0   0.0362  0.6466     0.6270  0.6292   
3                       3382625.0   0.0348  0.6847     0.6490  0.6697   
4                       3505628.0   0.0286  0.7229     0.7189  0.7044   

  Reclamos-Cat  
0            4  
1            4  
2            4  
3            4  
4            4

In [ ]:
data["Reclamos-Cat"].value_counts().sort_index()

1     0
2     0
3     0
4    27
5    17
Name: Reclamos-Cat, dtype: int64

#XGboost - Shrinkage (alpha - lambda)

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                         15.12   

   N° total de horas de atención al mes      CSA%  \
0                               18518.0  0.000817   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                            41584.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES  DAP (%)  \
0                               493360.0   0.0843   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                      118385.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)   Bajas  Consultas   Altas  
0                       3124089.0   0.0379  0.6217     0.6588  0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333


##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                         15.12   

   N° total de horas de atención al mes      CSA%  \
0                               18518.0  0.000817   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                            41584.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES  DAP (%)  \
0                               493360.0   0.0843   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                      118385.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)   Bajas  Consultas   Altas  
0                       3124089.0   0.0379  0.6217     0.6588  0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333


##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                         15.12   

   N° total de horas de atención al mes      CSA%  \
0                               18518.0  0.000817   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                            41584.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES  DAP (%)  \
0                               493360.0   0.0843   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                      118385.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)   Bajas  Consultas   Altas  
0                       3124089.0   0.0379  0.6217     0.6588  0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier()

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333


##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

AÑO  Mes  N° de horas sin sistema de atención al mes    \
0  1.0  9.0                                         15.12   

   N° total de horas de atención al mes      CSA%  \
0                               18518.0  0.000817   

   Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES  \
0                                            41584.0      

   Nº TOTAL DE USUARIOS ATENDIDOS AL MES  DAP (%)  \
0                               493360.0   0.0843   

   Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO  \
0                                      118385.0   

   Nº TOTAL DE LLAMADAS ATENDIDAS  CAT (%)   Bajas  Consultas   Altas  
0                       3124089.0   0.0379  0.6217     0.6588  0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333


#XGboost - Con RFE

##RFE

In [ ]:
from sklearn import linear_model
from time import time
import numpy as np
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

df = data.dropna()
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

#######################################
#no of features
nof_list=np.arange(1,14)            
high_score=0
#Variable to store the optimum features
nof=0           
score_list =[]
for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)
    model = LinearRegression()
    rfe = RFE(model,nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)
    score = model.score(X_test_rfe,y_test)
    score_list.append(score)
    if(score>high_score):
        high_score = score
        nof = nof_list[n]
print("Optimum number of features: %d" %nof)
print("Score with %d features: %f" % (nof, high_score))
#########################################
cols = list(X.columns)
model = LinearRegression()
#Initializing RFE model
rfe = RFE(model, 8)             
#Transforming data using RFE
X_rfe = rfe.fit_transform(X,Y)  
#Fitting the data to model
model.fit(X_rfe,Y)              
temp = pd.Series(rfe.support_,index = cols)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Optimum number of features: 8
Score with 8 features: 0.438011
Index(['Mes', 'N° de horas sin sistema de atención al mes  ', 'CSA%',
       'DAP (%)', 'CAT (%)', 'Bajas', 'Consultas', 'Altas'],
      dtype='object')


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=4 as keyword args. From version 1.0 (renaming of 0.25) passing these 

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['Mes',
        'N° de horas sin sistema de atención al mes  ',
        'CSA%',
        'DAP (%)',
        'CAT (%)',
        'Bajas',
        'Consultas',
        'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

Mes  N° de horas sin sistema de atención al mes        CSA%  DAP (%)  \
0  9.0                                         15.12  0.000817   0.0843   

   CAT (%)   Bajas  Consultas   Altas  
0   0.0379  0.6217     0.6588  0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333


##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['Mes',
        'N° de horas sin sistema de atención al mes  ',
        'CSA%',
        'DAP (%)',
        'CAT (%)',
        'Bajas',
        'Consultas',
        'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

Mes  N° de horas sin sistema de atención al mes        CSA%  DAP (%)  \
0  9.0                                         15.12  0.000817   0.0843   

   CAT (%)   Bajas  Consultas   Altas  
0   0.0379  0.6217     0.6588  0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333


##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['Mes',
        'N° de horas sin sistema de atención al mes  ',
        'CSA%',
        'DAP (%)',
        'CAT (%)',
        'Bajas',
        'Consultas',
        'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

Mes  N° de horas sin sistema de atención al mes        CSA%  DAP (%)  \
0  9.0                                         15.12  0.000817   0.0843   

   CAT (%)   Bajas  Consultas   Altas  
0   0.0379  0.6217     0.6588  0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier()

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333


##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['Mes',
        'N° de horas sin sistema de atención al mes  ',
        'CSA%',
        'DAP (%)',
        'CAT (%)',
        'Bajas',
        'Consultas',
        'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

Mes  N° de horas sin sistema de atención al mes        CSA%  DAP (%)  \
0  9.0                                         15.12  0.000817   0.0843   

   CAT (%)   Bajas  Consultas   Altas  
0   0.0379  0.6217     0.6588  0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333
